# casc-fix.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jenkins-jcasc-config
  namespace: jenkins
  # Helm이 관리하도록 관련 레이블을 유지합니다.
  labels:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-5.8.73
    jenkins-jenkins-config: "true"
data:
  jcasc-default-config.yaml: |-
    jenkins:
      numExecutors: 0
      clouds:
      - kubernetes:
          name: "kubernetes"
          namespace: "jenkins"
          jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
          credentialsId: "KUBERNETES_SERVICE_ACCOUNT"
          skipTlsVerify: true
          podLabels:
          - key: "jenkins"
            value: "slave"
