# final-jenkins-values.yaml
controller:
  serviceType: LoadBalancer
  
  # ❗ JNLP 에이전트 통신을 위한 서비스 설정을 명시적으로 추가
  agentListenerService:
    type: ClusterIP
    servicePort: 50000

  installPlugins: []

  JCasC:
    enabled: false
