# final-jenkins-values.yaml
controller:
  serviceType: LoadBalancer
  
  # installPlugins 섹션을 비워두어 Helm Chart 기본값을 사용하도록 함
  installPlugins: []

  JCasC:
    enabled: false # JCasC도 비활성화하여 충돌 가능성 최소화
