apiVersion: v1
kind: Config
current-context: gke_kwon-cicd_asia-northeast3-a_cicd-gke-cluster
clusters:
- name: gke_kwon-cicd_asia-northeast3-a_cicd-gke-cluster
  cluster:
    server: https://34.64.184.207
    certificate-authority-data: DATA+OMITTED
contexts:
- name: gke_kwon-cicd_asia-northeast3-a_cicd-gke-cluster
  context:
    cluster: gke_kwon-cicd_asia-northeast3-a_cicd-gke-cluster
    user: jenkins
    namespace: jenkins
users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InJEYlZtWkFXaXZEREdwWDBJdzZHZzFlUEZ3b2RZM19MeGxHRHRVU0FPYkEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJqZW5raW5zIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtdG9rZW4tc2VjcmV0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImplbmtpbnMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJhNDI0MTBjNy1kZTM0LTQ1ZTEtYjQzZi05YmVkOTFiOTA3NzciLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6amVua2luczpqZW5raW5zIn0.iZe64UJfkCrr35qZ0A-lvMCmFJ1noF-DqzQsvDLlBTEe0SDoNndvrHRvD-zuwl0S7fy5vCPlFUaTumpdO3ErQ0WeGMtaJlpNKjUdM7VcAEN9qk-IjfVo1egAht8Lj4v6fvKLaKZ1sqcZqpKutUENXI2yjl7NveHe8qzcs3WMlhz-v56DwY8YvB7c3ED0amuDlxdI004I2jZl-Zx41QfUHzNxZXiUpElN5Bafqa3CPbwxye18Cm4HKIZLiHw9Uzq0Vz0aLaNfpnZZ3SXHraD81R5zRIXVeFiKDeLU8UGLlXuSz6fw3s98XRu8a5K3P3z7ZLTkQwyj1weHmx1bZLjngg
