apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server-container
        # 이 부분은 나중에 Jenkins가 빌드된 이미지 주소로 자동 변경해줍니다.
        image: placeholder
        ports:
        - containerPort: 8080
