# helm-chart/my-web-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-server-backend-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: web-server-backend
